#!/bin/sh
# FIXME: this takes for granted that we already are in the right cwd.
# Our shell script prints to stdetrr, so in order to log that as well
# we have to redirect stderr to stdout
exec 2>&1
cd /home/grota/Projects/devops/runit_tests
exec sv/rand_with_stderr/pseudo_daemon.sh
